name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [django, dashboard]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/python -m pip install -r requirements.txt

      - name: Run tests for ${{ matrix.app }}
        run: |
          ./venv/bin/python -m pytest apps/${{ matrix.app }}/tests --cov=apps/${{ matrix.app }} --cov-report=xml --cov-branch --junitxml=reports/${{ matrix.app }}-junit.xml
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: ${{ matrix.app }}
          name: codecov_demo
          fail_ci_if_error: true
